In [4]:
import numpy as np

def prepare_sequences(file_path, sequence_length=30):
    data = np.load(file_path, allow_pickle=True).astype(np.float16)
    sequences = []
    for i in range(len(data) - sequence_length ):
        sequence = data[i:i + sequence_length]
        sequences.append(sequence)
    sequences = np.array(sequences)

    return sequences

# a_sequences = prepare_sequences(r'C:\Users\oem\Desktop\jhy\dataset2\(It is impossible)\raw_1707385020.npy')



In [21]:
### test
import numpy as np
import os
import glob
from tensorflow.python.client import device_lib
import tensorflow as tf
# print(device_lib.list_local_devices())
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

import numpy as np
from tqdm import tqdm
import os
import glob  # glob 라이브러리 추가
import pickle
from tensorflow.keras.utils import to_categorical
from datetime import datetime
import random

start_time = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
os.makedirs(f'C:/Users/oem/Desktop/jhy/array/{start_time}',exist_ok=True)

# dataset 폴더 경로 설정
# PATH = '/content/drive/MyDrive/LAB/Sign_Language_Remaster/code/lstm/dataset'
PATH = r'C:/Users/oem/Desktop/jhy/dataset'

# dataset 폴더 아래의 모든 폴더 목록을 얻기
actions = []  # 변경된 부분
label_mapping = {}  # 변경된 부분

### 액션 리스트 확인
for folder in os.listdir(PATH):
    if os.path.isdir(os.path.join(PATH, folder)):
        # 각 폴더에 있는 npy 파일들을 확인
        npy_files = glob.glob(os.path.join(PATH, folder, 'seq_*.npy'))
        # 특정 조건에 맞는 npy 파일이 존재하면 actions와 label_mapping에 추가
        if npy_files:
            actions.append(folder)
            label_mapping[folder] = len(actions) - 1
print(len(actions),'are ready')

# 리스트를 파일로 저장
with open(r'C:/Users/oem/Desktop/jhy/signlanguage/Sign_Language_Remaster/logs/act_list.pkl', 'wb') as f:
    pickle.dump(actions, f)



################################################################################################################################

def create_groups(data_count, group_size, appearances_per_data):
    # 데이터셋 초기화
    datasets = list(range(0, data_count ))
    random.shuffle(datasets)

    # 각 데이터의 사용 횟수를 추적하는 딕셔너리
    usage_count = {dataset: 0 for dataset in datasets}
   
    # 그룹을 저장할 리스트
    groups = []
   
    # 현재 그룹
    current_group = []
   
    # 데이터셋을 순환하면서 그룹 생성
    for _ in range(appearances_per_data):
        for dataset in datasets:
            # 현재 그룹에 데이터 추가
            current_group.append(dataset)
            usage_count[dataset] += 1
           
            # 현재 그룹이 가득 찼거나 모든 데이터가 사용된 경우 그룹 저장 및 초기화
            if len(current_group) == group_size or all(usage_count[dataset] == appearances_per_data for dataset in datasets):
                groups.append(current_group)
                current_group = []
   
    return groups

# 4000개의 데이터셋으로 크기가 500인 그룹을 만들고, 각 데이터가 3번씩 포함되도록 그룹 생성
groups = create_groups(len(actions), 400, 3)
print(len(groups),'개 그룹이 만들어질 예정입니다.')
for group_idx, group in tqdm(enumerate(groups)):
    data = []
    labels = []
    # print(len(group))
    for act_idx in group:
        # print(act_idx)
        action = actions[act_idx]
    
################################################################################################################################
        PATH2 = os.path.join(PATH, action) #/dataset/{action}
        file_path = glob.glob(os.path.join(PATH2, f'raw_*.npy'))[0]
        try:
            loaded_data = prepare_sequences(file_path)
            # loaded_data = np.load(file_path, allow_pickle=True).astype(np.float16)
            data.append(loaded_data)
################################################################################################################################

            label = np.full((loaded_data.shape[0],), label_mapping[action])
            labels.append(label)
        except FileNotFoundError:
            print(f"File not found for action: {action}")

    x_data = np.concatenate(data, axis=0)
    labels = np.concatenate(labels, axis=0)
    y_data = to_categorical(labels, num_classes=len(actions))

    np.savez_compressed(f'C:/Users/oem/Desktop/jhy/array/{start_time}/{group_idx}_XData',x_data)
    np.savez_compressed(f'C:/Users/oem/Desktop/jhy/array/{start_time}/{group_idx}_YData',y_data)

Num GPUs Available:  4
1645 are ready
13 개 그룹이 만들어질 예정입니다.


0it [00:00, ?it/s]

1026
752
1490
1395
1627
982
455
167
189
0
718
421
655
1386
600
1495
1323
535
1190
423
578
1551
1555
64
678
778
942
210
160
390
1572
86
1330
1336
965
524
158
1037
1610
842
593
1354
1523
164
1079
652
774
1553
169
435
484
234
475
948
1154
409
250
554
872
1416
1311
1005
15
836
990
815
318
704
795
1098
81
587
1483
1213
416
1522
1613
138
52
1411
211
1413
1300
1176
1212
889
922
325
912
497
269
1350
67
1140
1179
1150
426
344
761
439
534
560
1283
1172
26
1146
829
1516
104
231
1025
1253
311
128
1558
449
1071
1078
1110
574
32
983
398
1207
1496
1215
1063
1034
1389
174
747
544
368
866
862
1360
811
640
923
1452
1347
924
518
12
1198
432
28
1096
180
959
1046
147
768
132
473
1529
1519
1597
1210
451
763
115
920
413
1088
309
1219
304
1281
1356
437
337
1329
867
1085
703
958
492
507
616
816
607
914
78
713
546
1083
74
371
119
844
1497
1521
1309
978
429
770
1377
428
1280
740
1459
1451
1248
633
550
1148
1423
239
1494
1639
649
1180
972
657
832
1379
516
1145
262
783
1498
1487
209
728
881
1514
1192
1542
880
294


0it [00:12, ?it/s]

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
